# Generated by Django 5.2 on 2025-04-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_itens', models.IntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
