# Generated by Django 5.2 on 2025-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_produto_remove_comanda_quantidade_itens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='produtos',
        ),
        migrations.AddField(
            model_name='comanda',
            name='quantidade_itens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comanda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ItemComanda',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
