# Generated by Django 5.2 on 2025-04-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_remove_comanda_produtos_comanda_quantidade_itens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='quantidade_itens',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='comanda',
            name='produtos',
            field=models.ManyToManyField(related_name='comandas', to='comandas.produto'),
        ),
    ]
