# Generated by Django 5.2 on 2025-04-15 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_produto_remove_comanda_quantidade_itens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='produtos',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='senha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comandas.comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandas.produto')),
            ],
        ),
    ]
