# Generated by Django 5.2 on 2025-04-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0006_remove_comanda_hora_remove_comanda_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='senha',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
